// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fHRkGM0IjXZjCksyEGOKgcWbIdiAPos',
    appId: '1:838191270725:web:275b07826905da5a8bcc2c',
    messagingSenderId: '838191270725',
    projectId: 'work-life-balance-ae28f',
    authDomain: 'work-life-balance-ae28f.firebaseapp.com',
    storageBucket: 'work-life-balance-ae28f.appspot.com',
    measurementId: 'G-SJCYS3RZ4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB72bCCufqkhg8fEMY16P98DwJJ-ZqHmU',
    appId: '1:838191270725:android:960af1deedabf3938bcc2c',
    messagingSenderId: '838191270725',
    projectId: 'work-life-balance-ae28f',
    storageBucket: 'work-life-balance-ae28f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXYbFu3WtB5UUpc6DEzIh9JctQZ5HyuqU',
    appId: '1:838191270725:ios:742caca16b024f7d8bcc2c',
    messagingSenderId: '838191270725',
    projectId: 'work-life-balance-ae28f',
    storageBucket: 'work-life-balance-ae28f.appspot.com',
    iosBundleId: 'com.example.worklifebalance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXYbFu3WtB5UUpc6DEzIh9JctQZ5HyuqU',
    appId: '1:838191270725:ios:659f747bc6077ac58bcc2c',
    messagingSenderId: '838191270725',
    projectId: 'work-life-balance-ae28f',
    storageBucket: 'work-life-balance-ae28f.appspot.com',
    iosBundleId: 'com.example.worklifebalance.RunnerTests',
  );
}
